Name = "r1soft"
Env = "dev"
Dept = "IT"
Created_by = "JC"
vpc = "vpc-3b472741"
ami = "ami-0b898040803850657"
instance_type = "t2.micro"
user = "ec2-user"
domain = "mydomain.com"
zone_id = "ZSBY94ENV7WM4" #Route 53 
record = "r1soft" #from the left everything before . in an actual domain called 'record'
key_name = "developer_key"