Name        = "jenkins"
Env         = "dev"
Dept        = "IT"
Created_by  = "Chyngyzkan Samatov"
vpc         = "vpc-e0d5318b" #us-east-2
ami         = "ami-0d8f6eb4f641ef691" #us-east-2
instance_type = "t2.micro"
user        = "ec2-user"
domain      = "csamatov.net"
zone_id     = "Z6XWWD56QDJWX" #my hosted zone  
record      = "buildserver" #from the left side everything before . called 'record'
associate_public_ip_address = true
